export const DataDummy = () => {
    return [
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Sederhana",
        desc: "Pelajari langkah-langkah makeup sederhana untuk tampilan natural dan segar setiap hari.",
        level: "pemula",
        duration: {
          date: "22/08/2024",
          time: "10.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "public/img/other-pelatihan-1.jpg", 
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "public/assets/img/other-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "public/assets/img/other-pelatihan-3.jpg",
          },
        ],
        price: "22800",
        materi: [
          "Persiapan kulit sebelum makeup.",
          "Pilihan foundation dan concealer yang ringan.",
          "Teknik pengaplikasian blush on yang tepat.",
          "Makeup mata natural dengan eyeshadow tipis.",
          "Pilihan lipstik yang cocok untuk tampilan natural.",
        ],
        about:
          "Kursus ini akan membahas dasar-dasar makeup untuk menciptakan tampilan minimalis namun elegan yang cocok digunakan untuk kegiatan sehari-hari.",
        mentor: "Elsa Carroll",
        location: "jakarta",
        headline_img: "/public/img/other-pelatihan-3.jpg",
        image_mentor: "/public/img/person-pelatihan-1.jpg",
        id: "1",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Sehari-hari",
        desc: "Belajar makeup praktis dan cepat untuk tampilan fresh setiap hari.",
        level: "pemula",
        duration: {
          date: "24/08/2024",
          time: "12.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/other-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/other-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/other-pelatihan-3.jpg",
          },
        ],
        price: "22800",
        materi: [
          "Cara memilih produk yang tahan lama untuk aktivitas harian.",
          "Tips menjaga makeup tetap segar sepanjang hari.",
          "Teknik contouring dan highlighting dasar.",
          "Makeup mata simpel dengan eyeliner.",
          "Pilihan lipstik yang sesuai dengan suasana hari.",
        ],
        about:
          "Di kursus ini, kamu akan belajar bagaimana merias wajah dengan cepat dan efisien untuk kegiatan sehari-hari seperti bekerja, belanja, atau hangout",
        mentor: "Elsa Carroll",
        location: "bekasi",
        headline_img: "/assets/img/other-pelatihan-2.jpg",
        image_mentor: "/assets/img/person-pelatihan-2.jpg",
        id: "2",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup ke Kampus",
        desc: "Makeup natural dan ringan untuk tampilan fresh saat kuliah.",
        level: "pemula",
        duration: {
          date: "25/08/2024",
          time: "08.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/other-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/other-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/other-pelatihan-3.jpg",
          },
        ],
        price: "gratis",
        materi: [
          "Makeup simpel yang tahan lama untuk hari panjang di kampus.",
          "Produk-produk makeup yang ramah untuk kulit remaja.",
          "Cara mengatasi minyak berlebih pada wajah.",
          "Pilihan makeup mata yang tidak mencolok.",
          "Rekomendasi lipstik natural untuk tampilan segar.",
        ],
        about:
          "Kursus ini dirancang khusus untuk mahasiswa yang ingin tampil segar dan percaya diri di kampus tanpa terlihat berlebihan.",
        mentor: "Elsa Carroll",
        location: "tanggerang",
        headline_img: "/public/img/other-pelatihan-1.jpg",
        image_mentor: "/public/img/person-pelatihan-3.jpg",
        id: "3",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Pernikahan",
        desc: "Pelajari teknik makeup pernikahan yang glamor dan tahan lama untuk hari spesial",
        level: "ahli",
        duration: {
          date: "25/08/2024",
          time: "08.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/bride-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/bride-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/bride-pelatihan-3.png",
          },
        ],
        price: "80800",
        materi: [
          "Persiapan kulit sebelum makeup pernikahan.",
          "Teknik makeup tahan lama untuk acara seharian.",
          "Makeup mata dramatis untuk pengantin.",
          "Pemilihan produk yang tepat untuk acara formal.",
          "Sentuhan akhir dengan highlighter dan setting spray.",
        ],
        about:
          "Kursus ini akan membantu kamu menguasai makeup pernikahan, mulai dari makeup dasar hingga teknik-teknik profesional yang cocok untuk pengantin.",
        mentor: "Carroll",
        location: "jakarta",
        headline_img: "/public/img/bride-pelatihan-1.jpg",
        image_mentor: "/public/img/person-pelatihan-4.jpg",
        id: "4",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Cantik untuk Pernikahan Kamu",
        desc: "Tampil sempurna di hari pernikahanmu dengan teknik makeup profesional yang elegan.",
        level: "mahir",
        duration: {
          date: "29/08/2024",
          time: "14.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/bride-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/bride-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/bride-pelatihan-3.png",
          },
        ],
        price: "56300",
        materi: [
          "Teknik foundation dan contouring yang sempurna.",
          "Makeup mata smokey yang elegan.",
          "Pilihan lipstik yang cocok untuk acara formal.",
          "Setting makeup agar tahan sepanjang hari.",
          "Tips menyempurnakan detail makeup untuk foto.",
        ],
        about:
          "Di kursus ini, kamu akan mempelajari langkah-langkah makeup untuk menciptakan tampilan cantik dan memukau di hari pernikahan.",
        mentor: "Carroll",
        location: "bekasi",
        headline_img: "/public/img/bride-pelatihan-2.jpg",
        image_mentor: "/public/img/person-pelatihan-5.jpg",
        id: "5",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Tampil Memukau di Hari Spesial Kamu",
        desc: "Makeup glamor untuk memastikan kamu tampil memukau di acara pentingmu.",
        level: "menengah",
        duration: {
          date: "29/08/2024",
          time: "14.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/bride-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/bride-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/bride-pelatihan-3.png",
          },
        ],
        price: "56300",
        materi: [
          "Teknik makeup glamor dan dramatis.",
          "Makeup mata yang berani dengan warna-warna bold.",
          "Pemilihan foundation yang cocok untuk malam hari.",
          "Tips membuat alis dan bibir yang menonjol.",
          "Sentuhan akhir dengan produk glowing.",
        ],
        about:
          "Kursus ini memberikan panduan makeup untuk acara-acara spesial seperti pesta, gala, atau acara formal lainnya, di mana kamu ingin tampil lebih dari biasanya",
        mentor: "Carroll",
        location: "bekasi",
        headline_img: "/public/img/bride-pelatihan-3.png",
        image_mentor: "/public/img/person-pelatihan-6.jpg",
        id: "6",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Glowing di Pernikahan dengan Makeup Ini",
        desc: "Dapatkan tampilan glowing sempurna untuk hari pernikahanmu dengan makeup yang tahan lama.",
        level: "ahli",
        duration: {
          date: "30/08/2024",
          time: "17.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "pelatihan-1",
            url: "/public/img/bride-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "pelatihan-2",
            url: "/public/img/bride-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "pelatihan-3",
            url: "/public/img/bride-pelatihan-3.png",
          },
        ],
        price: "56300",
        materi: [
          "Persiapan kulit agar terlihat glowing.",
          "Penggunaan highlighter dan illuminator untuk efek glowing.",
          "Makeup mata dengan shimmer dan glitter.",
          "Teknik lipstik yang memberikan kesan segar.",
          "Setting makeup agar bertahan lama dan tetap glowing.",
        ],
        about:
          "Kursus ini mengajarkan cara mendapatkan efek kulit glowing dengan teknik makeup yang tepat untuk acara pernikahan.",
        mentor: "Carroll",
        location: "tanggerang",
        headline_img: "/public/img/pelatihan-3.png",
        image_mentor: "/public/img/person-pelatihan-6.jpg",
        id: "7",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Wisuda untuk Anak Kuliah",
        desc: "Tampil sempurna di acara wisuda dengan makeup yang natural dan elegan",
        level: "pemula",
        duration: {
          date: "30/08/2024",
          time: "17.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "student-pelatihan-1",
            url: "/public/img/student-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "student-pelatihan-2",
            url: "/public/img/student-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "student-pelatihan-3",
            url: "/public/img/student-pelatihan-3.png",
          },
        ],
        price: "20500",
        materi: [
          "Persiapan kulit sebelum makeup wisuda.",
          "Teknik makeup mata yang mempertegas bentuk mata.",
          "Pilihan lipstik dan blush on untuk tampilan segar.",
          "Cara membuat makeup tahan seharian di bawah toga.",
          "Tips merapikan alis dengan natural.",
        ],
        about:
          "Kursus ini dirancang untuk mahasiswa yang ingin tampil cantik dan profesional di hari wisuda, dengan teknik makeup yang sederhana tapi elegan",
        mentor: "Carroll",
        location: "bandung",
        headline_img: "/public/img/student-pelatihan-1.jpg",
        image_mentor: "/public/img/person-pelatihan-8.jpg",
        id: "8",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Tampil Cantik di Hari Terakhir Sekolah dengan Makeup Ini",
        desc: "Makeup ringan untuk tampilan cantik di hari terakhir sekolah",
        level: "pemula",
        duration: {
          date: "30/08/2024",
          time: "17.00 Pagi",
        },
        total_student: "10",
        portofolio: [
          {
            id: 1,
            name: "student-pelatihan-1",
            url: "/public/img/student-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "student-pelatihan-2",
            url: "/public/img/student-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "student-pelatihan-3",
            url: "/public/img/student-pelatihan-3.png",
          },
        ],
        price: "30500",
        materi: [
          "Dasar makeup ringan untuk tampilan fresh.",
          "Teknik makeup mata yang simpel dan tidak mencolok.",
          "Pilihan lipstik dan blush on untuk suasana ceria.",
          "Tips merawat kulit agar tetap sehat setelah makeup.",
          "Setting makeup agar bertahan hingga akhir acara.",
        ],
        about:
          "Di hari terakhir sekolah, tampil cantik namun natural dengan makeup yang sederhana tapi menarik. Kursus ini mengajarkan teknik makeup cepat dan mudah",
        mentor: "Carroll",
        location: "bekasi",
        headline_img: "/public/img/student-pelatihan-2.jpg",
        image_mentor: "/public/img/person-pelatihan-9.jpg",
        id: "9",
      },
      {
        createdAt: "2038-01-13T09:25:58.336Z",
        title: "Makeup Hari Terakhir untuk Kelulusan",
        desc: "Makeup spesial untuk merayakan hari kelulusan dengan tampilan yang cantik dan fresh.",
        level: "pemula",
        duration: {
          date: "01/08/2024",
          time: "20.00 Pagi",
        },
        total_student: "30",
        portofolio: [
          {
            id: 1,
            name: "student-pelatihan-1",
            url: "/public/img/student-pelatihan-1.jpg",
          },
          {
            id: 2,
            name: "student-pelatihan-2",
            url: "/public/img/student-pelatihan-2.jpg",
          },
          {
            id: 3,
            name: "student-pelatihan-3",
            url: "/public/img/student-pelatihan-3.png",
          },
        ],
        price: "30500",
        materi: [
          "Makeup dasar yang ringan namun tahan lama.",
          "Teknik makeup mata yang simpel namun mempertegas.",
          "Pilihan warna-warna cerah untuk lipstik.",
          "Cara menggunakan setting spray agar makeup bertahan.",
          "Tips membuat kulit terlihat glowing di foto.",
        ],
        about:
          "Kursus ini mengajarkan cara makeup untuk merayakan kelulusan, dengan tampilan yang segar dan elegan yang cocok untuk foto kelulusan",
        mentor: "Carroll",
        location: "bali",
        headline_img: "/public/img/student-pelatihan-3.jpg",
        image_mentor: "/public/img/person-pelatihan-10.jpg",
        id: "10",
      },
    ];
}